import zipfile
import re
import rasterio
from pathlib import Path

# ─── CONFIGURATION ──────────────────────────────────────────────────────────
# Point this to your historical track data
TRACK_KMZ = r"C:\Users\hamme\Desktop\APRS MAP TOOLS\Viewshed V2\APRS dataset\cleaned APRS running.kmz"

# Point this to the raw data raster generated by the viewshed script
COVERAGE_TIF = r"C:\Users\hamme\Desktop\APRS MAP TOOLS\Viewshed V2\aprs_viewshed_work\coverage_count.tif"

# Output file for visualizing the hits and misses
OUTPUT_KML = r"C:\Users\hamme\Desktop\APRS MAP TOOLS\Viewshed V2\validation_results.kml"
# ────────────────────────────────────────────────────────────────────────────

def extract_coords_from_kmz(kmz_path):
    """Extracts all Latitude/Longitude points from a KML/KMZ file."""
    coords = []
    print(f"Extracting historical points from {kmz_path}...")
    
    with zipfile.ZipFile(kmz_path, 'r') as z:
        # Find the KML file inside the KMZ archive
        kml_filename = [n for n in z.namelist() if n.endswith('.kml')][0]
        with z.open(kml_filename) as f:
            xml_data = f.read().decode('utf-8', errors='ignore')
            
    # 1. Parse standard <coordinates> blocks (lon,lat,alt)
    for block in re.findall(r'<coordinates>(.*?)</coordinates>', xml_data, re.DOTALL):
        for chunk in block.split():
            parts = chunk.split(',')
            if len(parts) >= 2:
                try:
                    coords.append((float(parts[0]), float(parts[1])))
                except ValueError:
                    pass

    # 2. Parse Google Earth Track <gx:coord> blocks (lon lat alt)
    for block in re.findall(r'<gx:coord>(.*?)</gx:coord>', xml_data):
        parts = block.split()
        if len(parts) >= 2:
            try:
                coords.append((float(parts[0]), float(parts[1])))
            except ValueError:
                pass
                
    print(f"  Found {len(coords)} historical ping(s).")
    return coords

def validate_coverage():
    coords = extract_coords_from_kmz(TRACK_KMZ)
    if not coords:
        print("❌ No coordinates found in the track file.")
        return

    print(f"\nChecking points against the terrain model ({COVERAGE_TIF})...")
    
    valid_coords = []
    out_of_bounds = 0

    with rasterio.open(COVERAGE_TIF) as src:
        bounds = src.bounds
        
        # Filter points to only those that fall inside the DEM area
        for lon, lat in coords:
            if (bounds.left <= lon <= bounds.right) and (bounds.bottom <= lat <= bounds.top):
                valid_coords.append((lon, lat))
            else:
                out_of_bounds += 1

        # Sample the raster at every historical coordinate
        results = []
        hits_count = 0
        misses_count = 0
        
        for point, val in zip(valid_coords, src.sample(valid_coords)):
            is_hit = val[0] > 0
            results.append((is_hit, point[0], point[1]))
            if is_hit:
                hits_count += 1
            else:
                misses_count += 1

    total_valid = hits_count + misses_count
    accuracy = (hits_count / total_valid) * 100 if total_valid > 0 else 0

    print("\n" + "="*50)
    print(" 📊 VALIDATION RESULTS")
    print("="*50)
    print(f" Total historical points : {len(coords)}")
    print(f" Points outside map area : {out_of_bounds}")
    print(f" Valid points checked    : {total_valid}")
    print("-" * 50)
    print(f" ✅ Model Hits (Covered)  : {hits_count}")
    print(f" ❌ Model Misses (Dead)   : {misses_count}")
    print(f" 📈 Model Accuracy        : {accuracy:.1f}%")
    print("="*50)

    # Convert individual points into continuous lines so Google Earth doesn't lag
    segments = build_lines(results)
    export_kml_lines(segments)

def build_lines(results):
    """Groups points into continuous lines. Breaks the line if there is a huge GPS gap."""
    segments = []
    if not results:
        return segments

    current_type = results[0][0]
    current_line = [(results[0][1], results[0][2])]
    
    for is_hit, lon, lat in results[1:]:
        prev_lon, prev_lat = current_line[-1]
        
        # Rough distance gap check (~2km) so we don't draw lines across the entire state 
        # if you turned your radio off and drove somewhere else.
        gap_size = ((lon - prev_lon)**2 + (lat - prev_lat)**2)**0.5
        
        if is_hit == current_type and gap_size < 0.02:
            current_line.append((lon, lat))
        else:
            if gap_size < 0.02:
                # Add the point to the old line so the green and red segments touch seamlessly
                current_line.append((lon, lat)) 
            
            if len(current_line) > 1:
                segments.append((current_type, current_line))
                
            current_line = [(lon, lat)]
            current_type = is_hit
            
    if len(current_line) > 1:
        segments.append((current_type, current_line))
        
    return segments

def export_kml_lines(segments):
    """Generates a KML using LineStrings (tracks) which Google Earth renders instantly."""
    print(f"\nGenerating {OUTPUT_KML} for visualization...")
    
    kml = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<kml xmlns="http://www.opengis.net/kml/2.2">',
        '<Document>',
        '  <name>APRS Model Validation Track</name>',
        # Define the Green and Red solid lines
        '  <Style id="hitLine">',
        '    <LineStyle><color>cc00ff00</color><width>5</width></LineStyle>',
        '  </Style>',
        '  <Style id="missLine">',
        '    <LineStyle><color>cc0000ff</color><width>5</width></LineStyle>',
        '  </Style>',
        '  <Folder><name>Validation Track</name>'
    ]

    for i, (is_hit, coords) in enumerate(segments):
        style = "hitLine" if is_hit else "missLine"
        name = "Coverage Hit" if is_hit else "Dead Zone Miss"
        
        # Format coordinates for KML LineString
        coord_str = " ".join([f"{lon},{lat},0" for lon, lat in coords])
        
        kml.append(f'    <Placemark>')
        kml.append(f'      <name>{name} {i}</name>')
        kml.append(f'      <styleUrl>#{style}</styleUrl>')
        kml.append(f'      <LineString>')
        kml.append(f'        <tessellate>1</tessellate>')
        kml.append(f'        <coordinates>{coord_str}</coordinates>')
        kml.append(f'      </LineString>')
        kml.append(f'    </Placemark>')

    kml.append('  </Folder>\n</Document>\n</kml>')

    with open(OUTPUT_KML, "w", encoding="utf-8") as f:
        f.write("\n".join(kml))
        
    print(f"Done! Drag and drop {OUTPUT_KML} into Google Earth.")

if __name__ == "__main__":
    validate_coverage()
